FROM nvcr.io/nvidia/nemo:24.01.speech
LABEL description="Pyannote pipeline para diarización"  
LABEL author="dasadeco (aka Daniel Sáenz de Cosca)" 

RUN apt-get update && apt-get install -y libsndfile1 ffmpeg
RUN pip3 install Cython packaging
RUN pip3 install argparse==1.4.0
RUN pip3 install omegaconf==2.3.0
RUN pip3 install pydub

WORKDIR /
COPY diarization/nemo_pipeline.py /
COPY diarization/nemo_import.py /
COPY diarization/keep_alive.py /
RUN mkdir -p /media
RUN chmod 777 /media

ENTRYPOINT ["python", "/keep_alive.py"]  